### ISSUE TITLE
webbpsf-data

### ISSUE THREAD

**Issue by exowanderer** [JarronL/pynrc#10]
Since the upgrade to `webbpsf` version 0.6.0, the `webbpsf-data-0.6.0.tar.gz` does not include the `OPD_RevV_nircam_132.fits` file.  I had to download the `webbpsf-data-0.5.0.tar.gz` and unpack it in the same directory as the `webbpsf-data-0.6.0.tar.gz`.  

That poses some version control issues, but so far so good.

I assume that v0.6.0 data includes the same information as v0.5.0 data, just in a different wrapper or format. But I don't know how to update this inside pynrc. I hope that this issue can be fixed without requiring to have 2 versions of the webbpsf-data files.

**Comment by JarronL** [comment]
Closing this because RevV OPDs are being deprecated and will no longer be supported.
