### ISSUE TITLE
implicit integer vs float division in nrc_utils

### ISSUE THREAD

**Issue by exowanderer** [JarronL/pynrc#11]
I’ve been having some stupid problems running Everett’s tso_sim code (github.com/eas342/tso_sims). `nrc_utils` keeps telling me that the array sizes did not match inside the `pynrc.nrc_utils` function.

I fixed this by going int the `pynrc/nrc_utils` file and changing all of the integer divisions form ` / 2` to ` // 2`, which is explicit integer division instead of implied float division -- for python3.

This fixed that problem. So I thought I’d let you know in case you ran into the same problem when trying to upgrade to python3

**Comment by JarronL** [comment]
Fixed!

**Comment by JarronL** [comment]
Fixed!
