### ISSUE TITLE
Coronagraph_Basics

### ISSUE THREAD

**Issue by abhijithrajan** [JarronL/pynrc#17]
notebook won't load.

**Comment by JarronL** [comment]
Thanks. This is a known issue from a conflicting git commit a few days ago. I've fixed it on my local machine, but haven't yet pushed it to github. Been a little swamped lately.

You'll probably notice that not all of the notebooks are going to work exactly right at the moment. I'm in the process of cleaning them up.

**Comment by JarronL** [comment]
In the meantime, you can check out the html version at https://pynrc.readthedocs.io/en/latest/tutorials/Coronagraph_Basics.html

**Comment by JarronL** [comment]
Notebook updated and uploaded.
