### ISSUE TITLE
Reducing Reference Pixels: Confusing message about xpix not 2048

### ISSUE THREAD

**Issue by eas342** [JarronL/pynrc#46]
* pyNRC version: 0.8.0dev
* Python version: 3.6.7
* Operating System: OS X

### Description
* Describe what you were trying to get done.:
Using `pynrc` to do reference pixel correction.
* Tell us what happened
The final result was good
* what went wrong,
You get a confusing message "In STRIPE mode, but xpix not 2048. Setting xpix=2048."
* what you expected to happen.
It does not give any warnings or messages because it is WINDOW data.

### What I Did

```python
import numpy as np
import pynrc

## make 256x2048 data
data = np.zeros([2,256,2048])
## make a header for it
detectorObj = pynrc.DetectorOps(xpix=256,ypix=2048,wind_mode='WINDOW',nint=1,read_mode='RAPID',ngroup=2)
head = detectorObj.make_header()
head['NGROUP'] = 2
head['NAXIS1'] = 256
head['NAXIS2'] = 2048
head['NINT'] = 1
head['READOUT'] = 'RAPID'

## try to do reference pixel corretion
ref_obj = pynrc.reduce.ref_pixels.NRC_refs(data,head)

```

I think the problem occurs on the 3rd line here:
```python
# Test if STRIPE or WINDOW
det_stripe = pynrc.DetectorOps(detector, 'STRIPE', xpix, ypix, x0, y0)
det_window = pynrc.DetectorOps(detector, 'WINDOW', xpix, ypix, x0, y0)
```
`pynrc.DetectorOps(detector, 'STRIPE', xpix, ypix, x0, y0)` is trying to make nonsensical data, so it gives the xpix=2048 message. But that just applies to this object and not your original input data.

Maybe you/one can make a `try` and `except` statement to catch this warning?

**Comment by JarronL** [comment]
Good point. I'll turn those print statements into log warnings and make sure to turn off warnings during that code snippet. Should be an easy fix. 

Also, no need to explicitly add in header information. You should just be able to consistently specify DMS headers as True or False.

```python

import numpy as np
import pynrc

## make 256x2048 data
data = np.zeros([2,256,2048])
## make a header for it
detectorObj = pynrc.DetectorOps(xpix=256,ypix=2048,wind_mode='WINDOW',nint=1,read_mode='RAPID',ngroup=2)
head = detectorObj.make_header(DMS=True)

## try to do reference pixel corretion
ref_obj = pynrc.reduce.ref_pixels.NRC_refs(data,head,DMS=True)

```

**Comment by JarronL** [comment]
Finally implemented fix for this.
